version: "3.7"
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports:
      - 51773:51773
      - 57772:57772
      - 1972:1972
      - 52773:52773
      - 443:443
    volumes:
      - ./:/irisdev
